import type { Config } from 'tailwindcss';

// Colors/spacing/radius below are read from CSS custom properties emitted by
// Style Dictionary (src/styles/tokens.css), generated from tokens/*.json.
// Run `npm run tokens:build` after changing tokens to regenerate that file.
const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}', './.storybook/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          500: 'var(--color-brand-500)',
          600: 'var(--color-brand-600)',
        },
        grey: {
          50: 'var(--color-grey-50)',
          200: 'var(--color-grey-200)',
          500: 'var(--color-grey-500)',
          900: 'var(--color-grey-900)',
        },
        success: { 500: 'var(--color-success-500)' },
        warning: { 500: 'var(--color-warning-500)' },
        danger: { 500: 'var(--color-danger-500)' },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          inverse: 'var(--text-inverse)',
          disabled: 'var(--text-disabled)',
        },
        surface: {
          default: 'var(--surface-default)',
          subtle: 'var(--surface-subtle)',
          secondary: 'var(--surface-secondary)',
          muted: 'var(--surface-muted)',
          border: 'var(--surface-border)',
          selected: 'var(--surface-selected)',
          disabled: 'var(--surface-disabled)',
        },
        action: {
          primary: 'var(--action-primary)',
          'primary-hover': 'var(--action-primary-hover)',
          theme: 'var(--action-theme)',
          'focus-ring': 'var(--action-focus-ring)',
        },
        feedback: {
          success: 'var(--feedback-success)',
          warning: 'var(--feedback-warning)',
          danger: 'var(--feedback-danger)',
          'success-tint': 'var(--color-overlay-success-20)',
          'warning-tint': 'var(--color-overlay-warning-20)',
          'danger-tint': 'var(--color-overlay-danger-20)',
        },
        toggle: {
          'track-on': 'var(--toggle-track-on)',
          'track-off': 'var(--toggle-track-off)',
          knob: 'var(--toggle-knob)',
        },
        'trend-pill': {
          'positive-bg': 'var(--trend-pill-positive-bg)',
          'positive-fg': 'var(--trend-pill-positive-fg)',
          'negative-bg': 'var(--trend-pill-negative-bg)',
          'negative-fg': 'var(--trend-pill-negative-fg)',
        },
        'delivery-status': {
          delivering: 'var(--delivery-status-delivering)',
          limited: 'var(--delivery-status-limited)',
          'not-delivering': 'var(--delivery-status-not-delivering)',
        },
        // AI Pilot feature accent scales — bqool-demo's Pilot/Insight surfaces use
        // Tailwind's default indigo/blue/slate/emerald/amber/sky/rose hues directly,
        // a distinct palette from the rest of the dashboard's brand/grey/feedback tokens.
        'ai-indigo': {
          50: 'var(--color-ai-indigo-50)',
          100: 'var(--color-ai-indigo-100)',
          200: 'var(--color-ai-indigo-200)',
          300: 'var(--color-ai-indigo-300)',
          500: 'var(--color-ai-indigo-500)',
          600: 'var(--color-ai-indigo-600)',
          700: 'var(--color-ai-indigo-700)',
          800: 'var(--color-ai-indigo-800)',
          900: 'var(--color-ai-indigo-900)',
          950: 'var(--color-ai-indigo-950)',
        },
        'ai-violet': { 500: 'var(--color-ai-violet-500)' },
        'ai-blue': {
          50: 'var(--color-ai-blue-50)',
          100: 'var(--color-ai-blue-100)',
          500: 'var(--color-ai-blue-500)',
          600: 'var(--color-ai-blue-600)',
          700: 'var(--color-ai-blue-700)',
          800: 'var(--color-ai-blue-800)',
          900: 'var(--color-ai-blue-900)',
        },
        'ai-slate': {
          50: 'var(--color-ai-slate-50)',
          100: 'var(--color-ai-slate-100)',
          200: 'var(--color-ai-slate-200)',
          300: 'var(--color-ai-slate-300)',
          400: 'var(--color-ai-slate-400)',
          500: 'var(--color-ai-slate-500)',
          600: 'var(--color-ai-slate-600)',
          700: 'var(--color-ai-slate-700)',
          900: 'var(--color-ai-slate-900)',
        },
        'ai-emerald': {
          50: 'var(--color-ai-emerald-50)',
          100: 'var(--color-ai-emerald-100)',
          200: 'var(--color-ai-emerald-200)',
          500: 'var(--color-ai-emerald-500)',
          700: 'var(--color-ai-emerald-700)',
          800: 'var(--color-ai-emerald-800)',
          950: 'var(--color-ai-emerald-950)',
        },
        'ai-amber': {
          50: 'var(--color-ai-amber-50)',
          100: 'var(--color-ai-amber-100)',
          200: 'var(--color-ai-amber-200)',
          700: 'var(--color-ai-amber-700)',
          800: 'var(--color-ai-amber-800)',
          950: 'var(--color-ai-amber-950)',
        },
        'ai-sky': {
          50: 'var(--color-ai-sky-50)',
          100: 'var(--color-ai-sky-100)',
          200: 'var(--color-ai-sky-200)',
          700: 'var(--color-ai-sky-700)',
        },
        'ai-rose': {
          50: 'var(--color-ai-rose-50)',
          100: 'var(--color-ai-rose-100)',
          200: 'var(--color-ai-rose-200)',
          500: 'var(--color-ai-rose-500)',
          700: 'var(--color-ai-rose-700)',
          800: 'var(--color-ai-rose-800)',
          950: 'var(--color-ai-rose-950)',
        },
        // Semantic groups for the AI Pilot / BQool Insight components
        'ai-mode': {
          'live-normal-bg': 'var(--ai-mode-live-normal-bg)',
          'live-normal-fg': 'var(--ai-mode-live-normal-fg)',
          'live-normal-border': 'var(--ai-mode-live-normal-border)',
          'live-inverted-bg': 'var(--ai-mode-live-inverted-bg)',
          'live-inverted-fg': 'var(--ai-mode-live-inverted-fg)',
          'live-inverted-border': 'var(--ai-mode-live-inverted-border)',
          'sandbox-normal-bg': 'var(--ai-mode-sandbox-normal-bg)',
          'sandbox-normal-fg': 'var(--ai-mode-sandbox-normal-fg)',
          'sandbox-normal-border': 'var(--ai-mode-sandbox-normal-border)',
          'sandbox-inverted-bg': 'var(--ai-mode-sandbox-inverted-bg)',
          'sandbox-inverted-fg': 'var(--ai-mode-sandbox-inverted-fg)',
          'sandbox-inverted-border': 'var(--ai-mode-sandbox-inverted-border)',
          'cached-normal-bg': 'var(--ai-mode-cached-normal-bg)',
          'cached-normal-fg': 'var(--ai-mode-cached-normal-fg)',
          'cached-normal-border': 'var(--ai-mode-cached-normal-border)',
          'cached-inverted-bg': 'var(--ai-mode-cached-inverted-bg)',
          'cached-inverted-fg': 'var(--ai-mode-cached-inverted-fg)',
          'cached-inverted-border': 'var(--ai-mode-cached-inverted-border)',
          'degraded-normal-bg': 'var(--ai-mode-degraded-normal-bg)',
          'degraded-normal-fg': 'var(--ai-mode-degraded-normal-fg)',
          'degraded-normal-border': 'var(--ai-mode-degraded-normal-border)',
          'degraded-inverted-bg': 'var(--ai-mode-degraded-inverted-bg)',
          'degraded-inverted-fg': 'var(--ai-mode-degraded-inverted-fg)',
          'degraded-inverted-border': 'var(--ai-mode-degraded-inverted-border)',
        },
        'ai-tone': {
          'critical-bg': 'var(--ai-tone-critical-bg)',
          'critical-border': 'var(--ai-tone-critical-border)',
          'critical-fg': 'var(--ai-tone-critical-fg)',
          'warning-bg': 'var(--ai-tone-warning-bg)',
          'warning-border': 'var(--ai-tone-warning-border)',
          'warning-fg': 'var(--ai-tone-warning-fg)',
          'opportunity-bg': 'var(--ai-tone-opportunity-bg)',
          'opportunity-border': 'var(--ai-tone-opportunity-border)',
          'opportunity-fg': 'var(--ai-tone-opportunity-fg)',
          'neutral-bg': 'var(--ai-tone-neutral-bg)',
          'neutral-border': 'var(--ai-tone-neutral-border)',
          'neutral-fg': 'var(--ai-tone-neutral-fg)',
          'limited-bg': 'var(--ai-tone-limited-bg)',
          'limited-border': 'var(--ai-tone-limited-border)',
          'limited-fg': 'var(--ai-tone-limited-fg)',
        },
        'ai-badge': {
          'critical-bg': 'var(--ai-badge-critical-bg)',
          'critical-fg': 'var(--ai-badge-critical-fg)',
          'warning-bg': 'var(--ai-badge-warning-bg)',
          'warning-fg': 'var(--ai-badge-warning-fg)',
          'opportunity-bg': 'var(--ai-badge-opportunity-bg)',
          'opportunity-fg': 'var(--ai-badge-opportunity-fg)',
          'neutral-bg': 'var(--ai-badge-neutral-bg)',
          'neutral-fg': 'var(--ai-badge-neutral-fg)',
          'accent-bg': 'var(--ai-badge-accent-bg)',
          'accent-fg': 'var(--ai-badge-accent-fg)',
        },
        'ai-confidence': {
          'high-bg': 'var(--ai-confidence-high-bg)',
          'high-fg': 'var(--ai-confidence-high-fg)',
          'moderate-bg': 'var(--ai-confidence-moderate-bg)',
          'moderate-fg': 'var(--ai-confidence-moderate-fg)',
          'low-bg': 'var(--ai-confidence-low-bg)',
          'low-fg': 'var(--ai-confidence-low-fg)',
        },
        // Component-level tokens for the two new AI Pilot templates
        'chat-bubble': {
          'user-bg': 'var(--chat-bubble-user-bg)',
          'user-fg': 'var(--chat-bubble-user-fg)',
          'assistant-fg': 'var(--chat-bubble-assistant-fg)',
          'assistant-caption-fg': 'var(--chat-bubble-assistant-caption-fg)',
        },
        'quick-skill-card': {
          bg: 'var(--quick-skill-card-bg)',
          border: 'var(--quick-skill-card-border)',
          'label-fg': 'var(--quick-skill-card-label-fg)',
          'description-fg': 'var(--quick-skill-card-description-fg)',
        },
        'ai-insight-panel': {
          'bg-from': 'var(--ai-insight-panel-bg-from)',
          'bg-via': 'var(--ai-insight-panel-bg-via)',
          'bg-to': 'var(--ai-insight-panel-bg-to)',
          'header-icon-bg': 'var(--ai-insight-panel-header-icon-bg)',
          'header-icon-border': 'var(--ai-insight-panel-header-icon-border)',
        },
        'execution-history-card': {
          bg: 'var(--execution-history-card-bg)',
          border: 'var(--execution-history-card-border)',
          'heading-fg': 'var(--execution-history-card-heading-fg)',
          'status-pill-bg': 'var(--execution-history-card-status-pill-bg)',
          'status-pill-fg': 'var(--execution-history-card-status-pill-fg)',
          'status-pill-ring': 'var(--execution-history-card-status-pill-ring)',
        },
        'execution-stage': {
          completed: 'var(--execution-stage-completed)',
          failed: 'var(--execution-stage-failed)',
          active: 'var(--execution-stage-active)',
          pending: 'var(--execution-stage-pending)',
        },
        'scope-card': {
          bg: 'var(--scope-card-bg)',
          border: 'var(--scope-card-border)',
          'label-fg': 'var(--scope-card-label-fg)',
          'value-fg': 'var(--scope-card-value-fg)',
          'value-fg-warning': 'var(--scope-card-value-fg-warning)',
        },
        'kpi-card': {
          bg: 'var(--kpi-card-bg)',
          border: 'var(--kpi-card-border)',
          'label-fg': 'var(--kpi-card-label-fg)',
          'value-fg': 'var(--kpi-card-value-fg)',
        },
        'finding-card': {
          bg: 'var(--finding-card-bg)',
          border: 'var(--finding-card-border)',
          'rank-bg': 'var(--finding-card-rank-bg)',
          'rank-fg': 'var(--finding-card-rank-fg)',
          'title-fg': 'var(--finding-card-title-fg)',
          'detail-fg': 'var(--finding-card-detail-fg)',
          'agent-fg': 'var(--finding-card-agent-fg)',
        },
        'recommendation-card': {
          bg: 'var(--recommendation-card-bg)',
          border: 'var(--recommendation-card-border)',
          'heading-fg': 'var(--recommendation-card-heading-fg)',
          'item-bg': 'var(--recommendation-card-item-bg)',
          'item-border': 'var(--recommendation-card-item-border)',
          'title-fg': 'var(--recommendation-card-title-fg)',
          'rationale-fg': 'var(--recommendation-card-rationale-fg)',
          'description-fg': 'var(--recommendation-card-description-fg)',
          'button-bg': 'var(--recommendation-card-button-bg)',
          'button-bg-hover': 'var(--recommendation-card-button-bg-hover)',
          'button-fg': 'var(--recommendation-card-button-fg)',
        },
        'generate-report-panel': {
          bg: 'var(--generate-report-panel-bg)',
          border: 'var(--generate-report-panel-border)',
          'heading-fg': 'var(--generate-report-panel-heading-fg)',
          'description-fg': 'var(--generate-report-panel-description-fg)',
          'outline-border': 'var(--generate-report-panel-outline-border)',
          'outline-fg': 'var(--generate-report-panel-outline-fg)',
          'solid-bg': 'var(--generate-report-panel-solid-bg)',
          'solid-bg-hover': 'var(--generate-report-panel-solid-bg-hover)',
        },
      },
      spacing: {
        'token-1': 'var(--space-1)',
        'token-2': 'var(--space-2)',
        'token-3': 'var(--space-3)',
        'token-4': 'var(--space-4)',
        'token-5': 'var(--space-5)',
        'token-6': 'var(--space-6)',
        'token-7': 'var(--space-7)',
        'token-8': 'var(--space-8)',
      },
      borderRadius: {
        'token-sm': 'var(--radius-sm)',
        'token-md': 'var(--radius-md)',
        'token-lg': 'var(--radius-lg)',
        'token-full': 'var(--radius-full)',
      },
      boxShadow: {
        resting: 'var(--elevation-resting)',
        raised: 'var(--elevation-raised)',
      },
      fontFamily: {
        sans: 'var(--font-family-sans)',
      },
    },
  },
  plugins: [],
};

export default config;
